// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/5/2026, 11:16:13 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/ryanj/OneDrive/Desktop/lunchcor/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/ryanj/OneDrive/Desktop/lunchcor/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/ryanj/OneDrive/Desktop/lunchcor/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/ryanj/OneDrive/Desktop/lunchcor/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/ryanj/OneDrive/Desktop/lunchcor/plugins/**/*.{js,ts,mjs}","C:/Users/ryanj/OneDrive/Desktop/lunchcor/composables/**/*.{js,ts,mjs}","C:/Users/ryanj/OneDrive/Desktop/lunchcor/utils/**/*.{js,ts,mjs}","C:/Users/ryanj/OneDrive/Desktop/lunchcor/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/ryanj/OneDrive/Desktop/lunchcor/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/ryanj/OneDrive/Desktop/lunchcor/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;